//!!!WARNING: This file is autogenerated and should not be modified manually.
export enum SubcatEvent {
  FeMenuDisable = "FeMenuDisable",
  BeMenuSelect = "BeMenuSelect",
  FeGenerate = "FeGenerate",
  BeGenerateRes = "BeGenerateRes",
}